### ISSUE TITLE
CSV com dados repetidos

### ISSUE THREAD

**Issue by rgamici** [seade-R/dados-covid-sp#1]
O arquivo csv disponibilizado repete os dados inúmeras vezes.
Sempre que a lista de cidades acaba, a lista recomeça com os mesmos dados, mesmo dia (mês como NA) e mesmos números de casos e mortes.
Deveriam ser os dados de dias anteriores?

**Comment by leobarone** [comment]
Havia um erro no arquivo anterior. Script para gerar o arquivo foi
corrigido e o arquivo novo está no ar.

Em qua., 22 de abr. de 2020 às 16:27, rgamici <notifications@github.com>
escreveu:

**Comment by rgamici** [comment]
Obrigado por resolver.
