### ISSUE TITLE
Leitos e internações por MUNICÍPIO

### ISSUE THREAD

**Issue by aroque-jundiai** [seade-R/dados-covid-sp#28]
Boa tarde.
Poderia passar a disponibilizar uma base semelhante à "plano_sp_leitos_internacoes_serie_nova_variacao_semanal.csv", mas por município ao invés de DRS?
Grato.

**Comment by leobarone** [comment]
Olá. Não há produção das variáveis desse arquivo para municípios. O menor
nível de agregação são os DRS. Abs

Em sex., 23 de abr. de 2021 às 14:18, aroque-jundiai <
***@***.***> escreveu:
