### ISSUE TITLE
Cidade Faltante no Relatório Dados Covid

### ISSUE THREAD

**Issue by sidneypino** [seade-R/dados-covid-sp#6]
Boa tarde, parabéns pelo trabalho.

Apenas gostaria de alertar alem dos casos IGNORADOS nos 3 relatórios dados_covid-sp faltam uma cidade São Luis do Paratinga

E desculpa pela minha ignorância, mas não pude entender o cálculo para as colunas casos_mm7d e obitos_mm7d. 

Muito obrigado.
Sidney Pino

**Comment by sidneypino** [comment]
Boa tarde, ignorados e São Luiz incluídos. E pude entender casos_mm7d e óbitos_mm7d.
Seria média aritmética dos últimos 7 dias. Obrigado.

**Comment by leobarone** [comment]
Desculpe a demora para responder. Fiz atualizações nos dados e informações
e espero que tenha resolvido suas dúvidas. Hoje foi ao ar uma segunda
página do painel para o qual organizamos esses dados:
https://www.seade.gov.br/coronavirus/


Em sex., 22 de mai. de 2020 às 18:56, sidneypino <notifications@github.com>
escreveu:
